### ISSUE TITLE
Merge vignettes

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/plant_paper#30]

**Comment by richfitz** [comment]
Need to go through and demote all headings by one.

**Comment by richfitz** [comment]
Changed mind on going through the headings and instead do this programmatically.

**Comment by richfitz** [comment]
I've merged all the code vignettes together into a single PDF complete with a table of contents.  It's not really clear to me how to get the latex/pdf ones in there though.

We can simply concatenate, but we really need things in the table of contents or they're absolutely undiscoverable.

We can convert the latex ones back into markdown as a final processing step, add them into the combined.md file, and turn into a PDF, but that might break things.

We can leave this as three pdfs (or combine the two latex ones and go with 2 pdfs).

Other ideas?

**Comment by dfalster** [comment]
Thanks Rich! 
I'm keen to go with 2 pdfs - latex based model description, html-based vignettes.

**Comment by dfalster** [comment]
addressed in aeacebe60f686a600dd3f5d1e58c885102ff7c7c and 5a05feaee5260f1b59679c3ffd19839f385879e0
